1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.


In [1]:
import numpy as np

a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [2]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [3]:
a = np.random.randint(1, 11, size=(5,5))
print(a)

[[ 5  7  2  2  3]
 [ 8  3  8  9  5]
 [ 6  7 10  6  6]
 [10  1  1 10  9]
 [ 9  2 10  3  7]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
a = np.random.rand(4, 4)
print(a)

[[0.19593155 0.51696701 0.36595145 0.46271689]
 [0.10241566 0.80358109 0.11246147 0.58169221]
 [0.50356876 0.12732767 0.60880063 0.51081647]
 [0.62682118 0.16818995 0.87108321 0.76080694]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
a = np.random.randint(1, 11, size=(5,))
b = np.random.randint(1, 11, size=(5,))
print('a:', a)
print('b:', b)
print('a + b:', a + b)
print('a - b:', a - b)
print('a * b:', a * b)

a: [8 1 3 6 9]
b: [1 3 5 6 8]
a + b: [ 9  4  8 12 17]
a - b: [ 7 -2 -2  0  1]
a * b: [ 8  3 15 36 72]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([8, 9, 10, 11, 12, 13, 14])
print(np.dot(a, b))

336


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [7]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(a)
print(b)
print(np.dot(a, b))

[[5 5]
 [4 4]]
[[ 8  8 10]
 [10  1  9]]
[[90 45 95]
 [72 36 76]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [8]:
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[5 2 9]
 [5 7 1]
 [3 8 9]]
[[ 0.1519337   0.14917127 -0.16850829]
 [-0.1160221   0.04972376  0.11049724]
 [ 0.05248619 -0.09392265  0.06906077]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [9]:
a = np.random.rand(4, 4)
print(a)
print(a.T)

[[0.41283188 0.35739592 0.16444446 0.03689722]
 [0.40426573 0.48497962 0.99738589 0.18149129]
 [0.26823965 0.88583196 0.14259557 0.16113461]
 [0.70634168 0.6983049  0.77392342 0.33627083]]
[[0.41283188 0.40426573 0.26823965 0.70634168]
 [0.35739592 0.48497962 0.88583196 0.6983049 ]
 [0.16444446 0.99738589 0.14259557 0.77392342]
 [0.03689722 0.18149129 0.16113461 0.33627083]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [10]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
print(a)
print(b)
print(np.dot(a, b))

[[ 8  4  3  5]
 [ 4  1  2  6]
 [ 2  1  6 10]]
[ 9 10  8 10]
[186 122 176]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [11]:
a = np.random.rand(2, 3)
b = np.random.rand(3)
print(a)
print(b)
print(np.dot(a, b))

[[0.69388315 0.38659596 0.9709078 ]
 [0.04324294 0.65460155 0.09669537]]
[0.75596543 0.07808022 0.74837695]
[1.28134218 0.15616618]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [12]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(a * b)

[[ 9  5]
 [ 9 10]]
[[ 6 10]
 [ 7  7]]
[[54 50]
 [63 70]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [13]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a)
print(b)
print(np.dot(a, b))

[[2 1]
 [5 9]]
[[9 7]
 [8 1]]
[[ 26  15]
 [117  44]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [14]:
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print(a.sum())

[[42 79  1 16 28]
 [86 14 56  9 80]
 [10  7 24  9 60]
 [31 97 63 56 53]
 [45 81  1 57 76]]
1081


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a)
print(b)
print(a - b)

[[ 3  8  6  1]
 [ 4  2  1  7]
 [ 5  9  3  4]
 [ 9  7 10 10]]
[[5 5 9 5]
 [6 9 1 4]
 [6 6 6 4]
 [2 7 3 8]]
[[-2  3 -3 -4]
 [-2 -7  0  3]
 [-1  3 -3  0]
 [ 7  0  7  2]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [16]:
a = np.random.rand(3, 3)
b = np.sum(a, axis=1)
print(a)
print(b)

[[0.57677245 0.26297649 0.48843941]
 [0.70832836 0.5815962  0.42219585]
 [0.8870681  0.880422   0.41749418]]
[1.32818835 1.7121204  2.18498429]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [17]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
b = np.square(a)
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
a = np.random.randint(1, 51, size=4)
b = np.sqrt(a)
print(a)
print(b)

[ 6 27 26 30]
[2.44948974 5.19615242 5.09901951 5.47722558]
